#!/usr/bin/env bash

#
# Pre-commit hook.
# The pre-commit hook will ensure that the following is available for the project:
#
#    - PHP is available for the terminal
#    - Composer.json has been downloaded for the project
#    - Composer is available for the project
#    - Ensure that vendor has been added to the .gitignore
#    - Composer has been run and vendors are available
#
# It then finds all scripts that are in tasks and will execute them
# prior to allowing the user to continue with a commit.
#

UPSTREAM=master
DIFF=`git diff --name-only $UPSTREAM`

ROOT="$(pwd)"

# Test to see if we're on the upstream branch.
CUR=`git rev-parse --abbrev-ref HEAD`
if [ $UPSTREAM == $CUR ]; then
  echo "Unable to run against the upstream branch, swap to a feature!"
  exit 0 # exit with 0 allows git commit to continue.
fi

# Locate the tasks that we should run before a commit.
# ------------------------------------------------------
TASKS=`find $ROOT/.git/hooks/tasks -iname "*.sh"`
for task in $TASKS
do
  sh $task $UPSTREAM $DIFF

  # Capture the exit status of the command, the git commit will be aborted if
  # we return a non-zero status.
  STATUS=$?
  if [ $STATUS -ne 0 ]; then
    exit $STATUS
  fi;
done
